media:
  input: public/images
  output: /images

content:
  - name: posts
    label: Posts
    path: src/content/posts
    type: collection
    format: yaml-frontmatter
    view:
      fields: [title, published, image]
      primary: title
      sort: [published]
      default:
        search: ""
        sort: published
        order: desc
    fields:
      - { name: title, label: Title, type: string, required: true }
      - { name: description, label: Description, type: string, required: true }
      - {
          name: published,
          label: Published Date,
          type: date,
          required: true,
          options: { time: true, format: yyyy-MM-dd'T'HH:mm },
        }
      - {
          name: draft,
          label: Draft,
          type: boolean,
          required: false,
          default: false,
        }
      - { name: category, label: Category, type: string, required: false }
      - { name: tags, label: Tags, type: string, list: true, required: false }
      - {
          name: image,
          label: Cover Image,
          type: image,
          required: false,
          options: { input: public/images, output: /images },
        }
      - { name: body, label: Body, type: rich-text, required: true }
